EXTRA_ECONF='--with-xscreensaverdir="${EPREFIX}/usr/share/xscreensaver/config" --with-xscreensaverhackdir="${EPREFIX}/usr/$(get_libdir)/misc/xscreensaver"'
EXTRA_EMAKE="DBUS_SESSION_SERVICE_DIR=$(pkg-config --variable session_bus_services_dir dbus-1)"
